[package]
name = "raddy-http"
version = "0.3.0"
edition = "2024"
license = "Apache-2.0"
description = "HTTP/1.1, HTTP/2, HTTP/3 QUIC servers, routing engine, and directives for Raddy"
repository = "https://github.com/fokx/raddy"
readme = "README.md"
keywords = ["caddy", "http", "http2", "http3", "quic"]
categories = ["network-programming", "web-programming::http-server"]

[dependencies]
raddy-core = { version = "0.3.0", path = "../raddy-core" }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1"
http = "1"
tracing = "0.1"
thiserror = "2"
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mime_guess = "2"
raddy-tls = { version = "0.3.0", path = "../raddy-tls" }
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pki-types = "1"
rustls-pemfile = "2"
raddy-proxy = { version = "0.3.0", path = "../raddy-proxy" }
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-aws-lc-rs"] }
h3 = "0.0.8"
h3-quinn = "0.0.10"
flate2 = "1.0"
zstd = "0.13"
bcrypt = "0.17"
base64 = "0.22"
minijinja = { version = "2", features = ["json"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2"] }
socket2 = "0.6"
chrono = "0.4.45"
ring = "0.17.14"
regex = "1.13.1"
tokio-util = { version = "0.7", features = ["io"] }
futures-util = "0.3"
httpdate = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
raddy-caddyfile = { version = "0.3.0", path = "../raddy-caddyfile" }


