[package]
name = "raddy-http"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
raddy-core = { path = "../raddy-core" }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1"
http = "1"
tracing = "0.1"
thiserror = "2"
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mime_guess = "2"
raddy-tls = { path = "../raddy-tls" }
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pki-types = "1"
rustls-pemfile = "2"
raddy-proxy = { path = "../raddy-proxy" }
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls-aws-lc-rs"] }
h3 = "0.0.8"
h3-quinn = "0.0.10"


[dev-dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2"] }

