[package]
name = "raddy-proxy"
version = "0.4.0"
edition = "2024"
license = "Apache-2.0"
description = "Reverse proxy, load balancers, health checks, and forward proxy for Raddy"
repository = "https://github.com/fokx/raddy"
readme = "README.md"
keywords = ["caddy", "reverse-proxy", "load-balancer", "forward-proxy", "raddy"]
categories = ["network-programming", "web-programming::http-server"]

[dependencies]
raddy-core = { version = "0.4.0", path = "../raddy-core" }
tokio = { version = "1", features = ["full"] }
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1"
http = "1"
tracing = "0.1"
thiserror = "2"
anyhow = "1"
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
parking_lot = "0.12"
base64 = "0.22"
ipnet = "2"
tokio-rustls = "0.26"
rustls = "0.23"
rustls-pki-types = "1"
rustls-native-certs = "0.8"
subtle = "2"
url = "2"
webpki-roots = "0.26"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
